DROP DATABASE IF EXISTS uppercasedb;
DROP USER IF EXISTS `uppercasedbadmin`@`%`;
CREATE DATABASE IF NOT EXISTS uppercasedb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `uppercasedbadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `uppercasedb`.* TO `uppercasedbadmin`@`%`;